In [2]:
import pandas as pd

food_info = pd.read_csv('food_info.csv')

In [3]:
food_info.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,3069.0,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,721.0,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,1080.0,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0

### Transformer une colonne

In [10]:
soduim_grams = food_info["Sodium_(mg)"]/1000
sugar_miligrams = food_info["Sugar_Tot_(g)"]*1000
sugar_miligrams

0          60.0
1          60.0
2           0.0
3         500.0
4         510.0
         ...
8613        0.0
8614        0.0
8615    73200.0
8616        0.0
8617        0.0
Name: Sugar_Tot_(g), Length: 8618, dtype: float64

### Opérations mathématiques entre colonnes

In [11]:
grams_of_per_gram_of_water = food_info["Protein_(g)"] / food_info["Water_(g)"]
miligrams_of_calcium_and_iron = food_info["Calcium_(mg)"] + food_info["Iron_(mg)"]
grams_of_per_gram_of_water

0       0.053560
1       0.053560
2       1.166667
3       0.504598
4       0.565313
          ...
8613    0.430233
8614    0.292384
8615    0.000000
8616    0.203283
8617    0.252229
Length: 8618, dtype: float64

### Créer un indice nutritionnel

In [18]:
# Score = 2*(Protein(g)) - 0.75*(LipidTot(g))
var_protein = 2 * food_info["Protein_(g)"]

var_lipid = -0.75 * food_info["Lipid_Tot_(g)"]

rating = var_protein + var_lipid

rating.head()

0   -59.1325
1   -59.1325
2   -74.0500
3    21.2450
4    24.2200
dtype: float64

### Normaliser une colonne

In [22]:
# series.max()
max_protein = food_info["Protein_(g)"].max()
normalized_protein = food_info["Protein_(g)"] / max_protein

max_lipid = food_info["Lipid_Tot_(g)"].max()
normalized_lipid = food_info["Lipid_Tot_(g)"] / max_lipid

normalized_protein.head()

0    0.009624
1    0.009624
2    0.003170
3    0.242301
4    0.263134
Name: Protein_(g), dtype: float64

### Créer une nouvelle colonne

In [23]:
food_info['Normalized_Protein'] = normalized_protein
food_info['Normalized_Fat'] = normalized_lipid

food_info.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Normalized_Protein,Normalized_Fat
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0,0.009624,0.8111
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0,0.009624,0.8111
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0,0.003170,0.9948
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0,0.242301,0.2874
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0,0.263134,0.2968

###  Créer une nouvelle colonne pour l'indice nutritionnel normalisé

In [24]:
# Score = 2*(Protein(g)) - 0.75*(LipidTot(g))
food_info["Norm_Nutr_Index"] = 2*food_info["Normalized_Protein"] - 0.75*food_info["Normalized_Fat"]

food_info.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Normalized_Protein,Normalized_Fat,Norm_Nutr_Index
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,1.5,60.0,7.0,51.368,21.021,3.043,215.0,0.009624,0.8111,-0.589077
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,1.5,60.0,7.0,50.489,23.426,3.012,219.0,0.009624,0.8111,-0.589077
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,1.8,73.0,8.6,61.924,28.732,3.694,256.0,0.003170,0.9948,-0.739759
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,0.5,21.0,2.4,18.669,7.778,0.800,75.0,0.242301,0.2874,0.269051
4,1005,CHEESE BRICK,41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,0.5,22.0,2.5,18.764,8.598,0.784,94.0,0.263134,0.2968,0.303668

### Trier un dataframe

In [25]:
# sort_values(col) : remplace pas l'originale
# sort_values(col, inplace = True, ascending = False ) : remplace l'originale
food_info.sort_values("Norm_Nutr_Index", inplace = True, ascending = False)
food_info.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Normalized_Protein,Normalized_Fat,Norm_Nutr_Index
4991,16423,SOY PROT ISOLATE K TYPE CRUDE PROT BASIS,4.98,321,88.32,0.53,3.58,2.59,2.0,0.0,...,0.0,0.0,0.0,0.066,0.101,0.258,0.0,1.000000,0.0053,1.996025
6155,19177,GELATINS DRY PDR UNSWTND,13.00,335,85.60,0.10,1.30,0.00,0.0,0.0,...,0.0,0.0,0.0,0.070,0.060,0.010,0.0,0.969203,0.0010,1.937656
216,1258,EGG WHITE DRIED STABILIZED GLUCOSE RED,6.53,362,84.63,0.48,3.63,4.72,0.0,0.0,...,0.0,0.0,0.0,0.147,0.173,0.070,20.0,0.958220,0.0048,1.912840
124,1136,EGG WHITE DRIED PDR STABILIZED GLUCOSE RED,8.54,376,82.40,0.04,4.55,4.47,0.0,0.0,...,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.932971,0.0004,1.865642
8152,35055,SEAL BEARDED (OOGRUK) MEAT DRIED (ALASKA NATIVE),11.60,351,82.60,2.30,3.50,0.00,0.0,0.0,...,NaN,NaN,NaN,0.600,1.330,0.370,NaN,0.935236,0.0230,1.853221